export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  CART_EMPTY: 'CART_EMPTY',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
  CANNOT_MODIFY_HIGHER_ROLE: 'CANNOT_MODIFY_HIGHER_ROLE',
  LAST_ADMIN: 'LAST_ADMIN',
  
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];